[theme]
base="dark"
primaryColor="#4ECCA3"
backgroundColor="#1A1A2E"
secondaryBackgroundColor="#232D3F"
textColor="#E6E6E6"
font="sans serif"

[server]
enableCORS=false
enableXsrfProtection=false
# Disable the file watcher to prevent conflicts with libraries like PyTorch
fileWatcherType = "none"
runOnSave = false  

[browser]
gatherUsageStats=false

[runner]
# These settings help prevent conflicts with PyTorch
magicEnabled=true
installTracer=false
fixMatplotlib=true

[global]
# Disables file watcher for problematic modules
disableWatchdogWarning=true
